### ISSUE TITLE
Ajouter un .gitignore dans le projet généré par cet archetype

### ISSUE THREAD

**Issue by ThomasLemaire** [DSI-Ville-Noumea/archetype-pandoc#1]

**Comment by noemienicolas** [comment]
Apres pas mal de recherche, il faut ajouter ce plugin dans le pom afin de ne pas exclure des choses par defaut : 

`
<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<version>3.0.2</version>
				<configuration>
					
					<addDefaultExcludes>false</addDefaultExcludes>
				</configuration>
			</plugin>
		</plugins>
`
