### ISSUE TITLE
Resoudre le soucis de l'image

### ISSUE THREAD

**Issue by noemienicolas** [DSI-Ville-Noumea/archetype-pandoc#2]
Dans le dossier images, on a une image, mais quand on utilise archetype pour generer un nouveau projet, cette image devient corrompue.

**Comment by adriens** [comment]
Ressoruces suir la question : http://maven.40175.n5.nabble.com/Possible-Archetype-Copy-bug-WRT-PNG-Images-td82501.html

Ca ressemble bien à un souci de copie des ressoruces qui est filtrée alors qu'elle ne devrait pas l'être

**Comment by adriens** [comment]
https://issues.apache.org/jira/browse/ARCHETYPE-25

**Comment by adriens** [comment]
regarder ceci et vérifier que c'est pas filtré : https://maven.apache.org/plugins/maven-resources-plugin/examples/copy-resources.html

**Comment by adriens** [comment]
:+1:
